version: '3.9'

services:
  jira:
    image: atlassian/jira-software:8.22.2
    container_name: jira
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      # 时区上海
      - TZ=Asia/Shanghai
      # 服务器环境变量
      - ATL_PROXY_NAME=${JIRA_PROXY_NAME:-jira.example.com}
      - ATL_PROXY_PORT=${JIRA_PROXY_PORT:-80}
      - ATL_TOMCAT_SCHEME=${JIRA_SCHEME:-http}
      - ATL_TOMCAT_SECURE=${JIRA_SECURE:-false}
      # 注册代理路径
      - JAVA_OPTS=-javaagent:/opt/atlassian/jira/atlassian-jira/WEB-INF/lib/atlassian-agent-1.3.1.jar
    volumes:
      # 数据卷
      - jira-data:/var/atlassian/application-data/jira
      # MySQL 8.0 连接器
      - ./utils/mysql-connector-java-8.0.29.jar:/opt/atlassian/jira/lib/mysql-connector-java-8.0.29.jar
      # 注册代理
      - ./utils/atlassian-agent-1.3.1.jar:/opt/atlassian/jira/atlassian-jira/WEB-INF/lib/atlassian-agent-1.3.1.jar
    networks:
      - atlassian

  confluence:
    image: atlassian/confluence:7.17.2
    container_name: confluence
    restart: unless-stopped
    ports:
      - 8090:8090
    environment:
      # 时区上海
      - TZ=Asia/Shanghai
      # 服务器环境变量
      - ATL_PROXY_NAME=${CONFLUENCE_PROXY_NAME:-confluence.example.com}
      - ATL_PROXY_PORT=${CONFLUENCE_PROXY_PORT:-80}
      - ATL_TOMCAT_SCHEME=${CONFLUENCE_SCHEME:-http}
      - ATL_TOMCAT_SECURE=${CONFLUENCE_SECURE:-false}
      # 注册代理路径
      - JAVA_OPTS=-javaagent:/opt/atlassian/confluence/confluence/WEB-INF/lib/atlassian-agent-1.3.1.jar
    volumes:
      # 数据卷
      - confluence-data:/var/atlassian/application-data/confluence
      # MySQL 8.0 连接器
      - ./utils/mysql-connector-java-8.0.29.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-java-8.0.29.jar
      # 注册代理
      - ./utils/atlassian-agent-1.3.1.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/atlassian-agent-1.3.1.jar
    networks:
      - atlassian

  bitbucket:
    image: atlassian/bitbucket:8.1.0
    container_name: bitbucket
    restart: unless-stopped
    ports:
      - 7990:7990
    environment:
      # 时区上海
      - TZ=Asia/Shanghai
      # 服务器环境变量
      - SERVER_PROXY_NAME=${BITBUCKET_PROXY_NAME:-bitbucket.example.com}
      - SERVER_PROXY_PORT=${BITBUCKET_PROXY_PORT:-80}
      - SERVER_SCHEME=${BITBUCKET_SCHEME:-http}
      - SERVER_SECURE=${BITBUCKET_SECURE:-false}
      # 注册代理路径
      - JVM_SUPPORT_RECOMMENDED_ARGS=-javaagent:/opt/atlassian/bitbucket/app/WEB-INF/lib/atlassian-agent-1.3.1-bitbucket.jar
    volumes:
      # 数据卷
      - bitbucket-data:/var/atlassian/application-data/bitbucket
      # MySQL 5.1 连接器（不支持 8.0 连接器）
      - ./utils/mysql-connector-java-5.1.49.jar:/opt/atlassian/bitbucket/app/WEB-INF/lib/mysql-connector-java-5.1.49.jar
      # 注册代理（不能生成授权码）
      - ./utils/atlassian-agent-1.3.1-bitbucket.jar:/opt/atlassian/bitbucket/app/WEB-INF/lib/atlassian-agent-1.3.1-bitbucket.jar
    networks:
      - atlassian

networks:
  atlassian:
    name: atlassian

volumes:
  jira-data:
  confluence-data:
  bitbucket-data:
