version: '3.9'

services:
  jira:
    image: atlassian/jira-software:latest
    container_name: jira
    restart: always
    ports:
      - 8080:8080
    environment:
      # 中国上海时区
      - TZ=Asia/Shanghai
      # 下面四个环境变量用来配置 /opt/atlassian/jira/conf/server.xml，参考自 /opt/atlassian/etc/server.xml.j2
      - ATL_TOMCAT_SECURE=${JIRA_SECURE:-false}
      - ATL_TOMCAT_SCHEME=${JIRA_SCHEME:-http}
      - ATL_PROXY_NAME=${JIRA_PROXY_NAME:-jira.example.com}
      - ATL_PROXY_PORT=${JIRA_PROXY_PORT:-80}
      # 注册代理路径
      - JAVA_OPTS=-javaagent:/opt/atlassian/atlassian-agent-1.3.1.jar
    volumes:
      # 数据卷
      - jira-data:/var/atlassian/application-data/jira
      # MySQL 8.0 连接器
      - ./utils/mysql-connector-java-8.0.29.jar:/opt/atlassian/jira/atlassian-jira/WEB-INF/lib/mysql-connector-java-8.0.29.jar
      # 注册代理
      - ./utils/atlassian-agent-1.3.1.jar:/opt/atlassian/atlassian-agent-1.3.1.jar
    networks:
      atlassian:
        aliases:
          - ${JIRA_PROXY_NAME:-jira.example.com}
        ipv4_address: 172.20.0.2
    depends_on:
      - jira-mysql

  confluence:
    image: atlassian/confluence-server:latest
    container_name: confluence
    restart: always
    ports:
      - 8090:8090
    environment:
      # 中国上海时区
      - TZ=Asia/Shanghai
      # 下面四个环境变量用来配置 /opt/atlassian/confluence/conf/server.xml，参考自 /opt/atlassian/etc/server.xml.j2
      - ATL_TOMCAT_SECURE=${CONFLUENCE_SECURE:-false}
      - ATL_TOMCAT_SCHEME=${CONFLUENCE_SCHEME:-http}
      - ATL_PROXY_NAME=${CONFLUENCE_PROXY_NAME:-confluence.example.com}
      - ATL_PROXY_PORT=${CONFLUENCE_PROXY_PORT:-80}
      # 注册代理路径
      - JAVA_OPTS=-javaagent:/opt/atlassian/atlassian-agent-1.3.1.jar
    volumes:
      # 数据卷
      - confluence-data:/var/atlassian/application-data/confluence
      # MySQL 8.0 连接器
      - ./utils/mysql-connector-java-8.0.29.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-java-8.0.29.jar
      # 注册代理
      - ./utils/atlassian-agent-1.3.1.jar:/opt/atlassian/atlassian-agent-1.3.1.jar
    networks:
      atlassian:
        aliases:
          - ${CONFLUENCE_PROXY_NAME:-confluence.example.com}
        ipv4_address: 172.20.0.3
    depends_on:
      - confluence-mysql

  bitbucket:
    image: atlassian/bitbucket-server:latest
    container_name: bitbucket
    restart: always
    ports:
      - 7990:7990
    environment:
      # 中国上海时区
      - TZ=Asia/Shanghai
      # 服务器环境变量
      - SERVER_SECURE=${BITBUCKET_SECURE:-false}
      - SERVER_SCHEME=${BITBUCKET_SCHEME:-http}
      - SERVER_PROXY_NAME=${BITBUCKET_PROXY_NAME:-bitbucket.example.com}
      - SERVER_PROXY_PORT=${BITBUCKET_PROXY_PORT:-80}
    volumes:
      # 数据卷
      - bitbucket-data:/var/atlassian/application-data/bitbucket
      # 自定义启动脚本
      - ./utils/_start-webapp.sh:/opt/atlassian/bitbucket/bin/_start-webapp.sh
      # MySQL 8.0 连接器
      - ./utils/mysql-connector-java-8.0.29.jar:/opt/atlassian/bitbucket/app/WEB-INF/lib/mysql-connector-java-8.0.29.jar
      # 注册代理（不能生成授权码）
      - ./utils/atlassian-agent-1.3.1-bitbucket.jar:/opt/atlassian/atlassian-agent-1.3.1-bitbucket.jar
    networks:
      atlassian:
        aliases:
          - ${BITBUCKET_PROXY_NAME:-bitbucket.example.com}
        ipv4_address: 172.20.0.4
    depends_on:
      - bitbucket-mysql

  jira-mysql:
    image: mysql:8.0
    container_name: jira-mysql
    restart: always
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_bin,
        --default-storage-engine=INNODB,
        --innodb-default-row-format=DYNAMIC,
        --innodb-log-file-size=2G
      ]
    environment:
      # 中国上海时区
      - TZ=Asia/Shanghai
      # root 密码
      - MYSQL_ROOT_PASSWORD=${JIRA_MYSQL_ROOT_PASSWORD:-atlassian}
      # 数据库名
      - MYSQL_DATABASE=${JIRA_MYSQL_DATABASE:-jira}
      # 用户名
      - MYSQL_USER=${JIRA_MYSQL_USER:-jira}
      # 密码
      - MYSQL_PASSWORD=${JIRA_MYSQL_PASSWORD:-jira}
    volumes:
      - jira-mysql:/var/lib/mysql
    networks:
      atlassian:
        ipv4_address: 172.20.0.5

  confluence-mysql:
    image: mysql:8.0
    container_name: confluence-mysql
    restart: always
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_bin,
        --default-storage-engine=INNODB,
        --max-allowed-packet=256M,
        --innodb-log-file-size=2G,
        --transaction-isolation=READ-COMMITTED,
        --binlog-format=ROW,
        --log-bin-trust-function-creators=1
      ]
    environment:
      # 中国上海时区
      - TZ=Asia/Shanghai
      # root 密码
      - MYSQL_ROOT_PASSWORD=${CONFLUENCE_MYSQL_ROOT_PASSWORD:-atlassian}
      # 数据库名
      - MYSQL_DATABASE=${CONFLUENCE_MYSQL_DATABASE:-confluence}
      # 用户名
      - MYSQL_USER=${CONFLUENCE_MYSQL_USER:-confluence}
      # 密码
      - MYSQL_PASSWORD=${CONFLUENCE_MYSQL_PASSWORD:-confluence}
    volumes:
      - confluence-mysql:/var/lib/mysql
    networks:
      atlassian:
        ipv4_address: 172.20.0.6

  bitbucket-mysql:
    image: mysql:8.0
    container_name: bitbucket-mysql
    restart: always
    command:
      [
        mysqld,
        --character-set-server=utf8,
        --collation-server=utf8_bin,
        --binlog-format=MIXED,
        --transaction-isolation=READ-COMMITTED
      ]
    environment:
      # 中国上海时区
      - TZ=Asia/Shanghai
      # root 密码
      - MYSQL_ROOT_PASSWORD=${BITBUCKET_MYSQL_ROOT_PASSWORD:-atlassian}
      # 数据库名
      - MYSQL_DATABASE=${BITBUCKET_MYSQL_DATABASE:-bitbucket}
      # 用户名
      - MYSQL_USER=${BITBUCKET_MYSQL_USER:-bitbucket}
      # 密码
      - MYSQL_PASSWORD=${BITBUCKET_MYSQL_PASSWORD:-bitbucket}
    volumes:
      - bitbucket-mysql:/var/lib/mysql
    networks:
      atlassian:
        ipv4_address: 172.20.0.7

networks:
  atlassian:
    name: atlassian
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  jira-data:
  confluence-data:
  bitbucket-data:
  jira-mysql:
  confluence-mysql:
  bitbucket-mysql:
