version: '3.9'

services:
  jira:
    image: atlassian/jira-software:latest
    container_name: jira
    restart: always
    environment:
      # 中国上海时区
      - TZ=Asia/Shanghai
      # 下面四个环境变量用来配置 /opt/atlassian/jira/conf/server.xml，参考自 /opt/atlassian/etc/server.xml.j2
      - ATL_TOMCAT_SECURE=${JIRA_SECURE:-false}
      - ATL_TOMCAT_SCHEME=${JIRA_SCHEME:-http}
      - ATL_PROXY_NAME=${JIRA_PROXY_NAME:-jira.example.com}
      - ATL_PROXY_PORT=${JIRA_PROXY_PORT:-80}
      # 注册代理路径
      - JAVA_OPTS=-javaagent:/opt/atlassian/atlassian-agent-1.3.1.jar
    volumes:
      # 数据卷
      - jira-data:/var/atlassian/application-data/jira
      # MySQL 8.0 连接器
      - ./utils/mysql-connector-java-8.0.29.jar:/opt/atlassian/jira/atlassian-jira/WEB-INF/lib/mysql-connector-java-8.0.29.jar
      # 注册代理
      - ./utils/atlassian-agent-1.3.1.jar:/opt/atlassian/atlassian-agent-1.3.1.jar
    networks:
      atlassian:
        aliases:
          - ${JIRA_PROXY_NAME:-jira.example.com}
        ipv4_address: 172.20.0.2
    depends_on:
      - nginx

  confluence:
    image: atlassian/confluence-server:latest
    container_name: confluence
    restart: always
    environment:
      # 中国上海时区
      - TZ=Asia/Shanghai
      # 下面四个环境变量用来配置 /opt/atlassian/confluence/conf/server.xml，参考自 /opt/atlassian/etc/server.xml.j2
      - ATL_TOMCAT_SECURE=${CONFLUENCE_SECURE:-false}
      - ATL_TOMCAT_SCHEME=${CONFLUENCE_SCHEME:-http}
      - ATL_PROXY_NAME=${CONFLUENCE_PROXY_NAME:-confluence.example.com}
      - ATL_PROXY_PORT=${CONFLUENCE_PROXY_PORT:-80}
      # 注册代理路径
      - JAVA_OPTS=-javaagent:/opt/atlassian/atlassian-agent-1.3.1.jar
    volumes:
      # 数据卷
      - confluence-data:/var/atlassian/application-data/confluence
      # MySQL 8.0 连接器
      - ./utils/mysql-connector-java-8.0.29.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-java-8.0.29.jar
      # 注册代理
      - ./utils/atlassian-agent-1.3.1.jar:/opt/atlassian/atlassian-agent-1.3.1.jar
    networks:
      atlassian:
        aliases:
          - ${CONFLUENCE_PROXY_NAME:-confluence.example.com}
        ipv4_address: 172.20.0.3
    depends_on:
      - nginx

  bitbucket:
    image: atlassian/bitbucket-server:latest
    container_name: bitbucket
    restart: always
    environment:
      # 中国上海时区
      - TZ=Asia/Shanghai
      # 服务器环境变量
      - SERVER_SECURE=${BITBUCKET_SECURE:-false}
      - SERVER_SCHEME=${BITBUCKET_SCHEME:-http}
      - SERVER_PROXY_NAME=${BITBUCKET_PROXY_NAME:-bitbucket.example.com}
      - SERVER_PROXY_PORT=${BITBUCKET_PROXY_PORT:-80}
    volumes:
      # 数据卷
      - bitbucket-data:/var/atlassian/application-data/bitbucket
      # 自定义启动脚本
      - ./utils/_start-webapp.sh:/opt/atlassian/bitbucket/bin/_start-webapp.sh
      # MySQL 8.0 连接器
      - ./utils/mysql-connector-java-8.0.29.jar:/opt/atlassian/bitbucket/app/WEB-INF/lib/mysql-connector-java-8.0.29.jar
      # 注册代理（不能生成授权码）
      - ./utils/atlassian-agent-1.3.1-bitbucket.jar:/opt/atlassian/atlassian-agent-1.3.1-bitbucket.jar
    networks:
      atlassian:
        aliases:
          - ${BITBUCKET_PROXY_NAME:-bitbucket.example.com}
        ipv4_address: 172.20.0.4
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - ${NGINX_PORT:-80}:80
    environment:
      # 中国上海时区
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      atlassian:
        ipv4_address: 172.20.0.5

networks:
  atlassian:
    name: atlassian
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  jira-data:
  confluence-data:
  bitbucket-data:
