version: '3.9'

services:
  jira:
    container_name: jira
    restart: always
    image: atlassian/jira-software:latest
    ports:
      - '8080:8080'
    environment:
      - JAVA_OPTS=-javaagent:/opt/atlassian/jira/atlassian-agent.jar
    volumes:
      - './jira/data:/var/atlassian/application-data/jira'
      - './mysql-connector-java-8.0.29.jar:/opt/atlassian/jira/atlassian-jira/WEB-INF/lib/mysql-connector-java-8.0.29.jar'
      - './atlassian-agent.jar:/opt/atlassian/jira/atlassian-agent.jar'
    networks:
      - jira-network
    depends_on:
      - jira-mysql

  jira-mysql:
    container_name: jira-mysql
    restart: always
    image: mysql:8.0
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_bin,
        --default-storage-engine=INNODB,
        --innodb_default_row_format=DYNAMIC,
        --innodb_log_file_size=2G
      ]
    environment:
      - MYSQL_ROOT_PASSWORD=atlassian
      - MYSQL_DATABASE=jira
      - MYSQL_USER=jira
      - MYSQL_PASSWORD=jira
    volumes:
      - './jira/mysql:/var/lib/mysql'
    networks:
      - jira-network

  confluence:
    container_name: confluence
    restart: always
    image: atlassian/confluence:latest
    ports:
      - '8090:8090'
      - '8091:8091'
    environment:
      - JAVA_OPTS=-javaagent:/opt/atlassian/confluence/atlassian-agent.jar
    volumes:
      - './confluence/data:/var/atlassian/application-data/confluence'
      - './mysql-connector-java-8.0.29.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-java-8.0.29.jar'
      - './atlassian-agent.jar:/opt/atlassian/confluence/atlassian-agent.jar'
    networks:
      - conf-network
    depends_on:
      - conf-mysql

  conf-mysql:
    container_name: conf-mysql
    restart: always
    image: mysql:8.0
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_bin,
        --default-storage-engine=INNODB,
        --max_allowed_packet=256M,
        --innodb_log_file_size=2G,
        --transaction-isolation=READ-COMMITTED,
        --binlog_format=row,
        --log_bin_trust_function_creators=1
      ]
    environment:
      - MYSQL_ROOT_PASSWORD=atlassian
      - MYSQL_DATABASE=confluence
      - MYSQL_USER=confluence
      - MYSQL_PASSWORD=confluence
    volumes:
      - './confluence/mysql:/var/lib/mysql'
    networks:
      - conf-network

networks:
  jira-network: {}
  conf-network: {}

volumes:
  jira:
  jira-mysql:
  confluence:
  conf-mysql:
