version: '3.9'

services:
  jira:
    image: atlassian/jira-software:${JIRA_VERSION:-latest}
    container_name: jira
    restart: unless-stopped
    ports:
      - ${JIRA_PORT:-8080}:8080
    environment:
      # 代理服务器
      - ATL_PROXY_NAME=${JIRA_PROXY_NAME:-jira.example.com}
      - ATL_PROXY_PORT=${JIRA_PROXY_PORT:-80}
      - ATL_TOMCAT_SCHEME=${JIRA_SCHEME:-http}
      - ATL_TOMCAT_SECURE=${JIRA_SECURE:-false}
      # 内存
      - JVM_MINIMUM_MEMORY=${JIRA_MINIMUM_MEMORY:-384m}
      - JVM_MAXIMUM_MEMORY=${JIRA_MAXIMUM_MEMORY:-768m}
      - JVM_RESERVED_CODE_CACHE_SIZE=${JIRA_RESERVED_CODE_CACHE_SIZE:-512m}
      # 注册代理路径
      - JAVA_OPTS=-javaagent:/opt/atlassian/jira/atlassian-jira/WEB-INF/lib/atlassian-agent-1.3.1.jar
      # 时区
      - TZ=Asia/Shanghai
    volumes:
      # 数据卷
      - jira-data:/var/atlassian/application-data/jira
      # MySQL 8.0 连接器
      - ./utils/mysql-connector-java-8.0.29.jar:/opt/atlassian/jira/lib/mysql-connector-java-8.0.29.jar
      # 注册代理
      - ./utils/atlassian-agent-1.3.1.jar:/opt/atlassian/jira/atlassian-jira/WEB-INF/lib/atlassian-agent-1.3.1.jar
    depends_on:
      - jira-mysql

  confluence:
    image: atlassian/confluence:${CONFLUENCE_VERSION:-latest}
    container_name: confluence
    restart: unless-stopped
    ports:
      - ${CONFLUENCE_PORT:-8090}:8090
    environment:
      # 代理服务器
      - ATL_PROXY_NAME=${CONFLUENCE_PROXY_NAME:-confluence.example.com}
      - ATL_PROXY_PORT=${CONFLUENCE_PROXY_PORT:-80}
      - ATL_TOMCAT_SCHEME=${CONFLUENCE_SCHEME:-http}
      - ATL_TOMCAT_SECURE=${CONFLUENCE_SECURE:-false}
      # 内存
      - JVM_MINIMUM_MEMORY=${CONFLUENCE_MINIMUM_MEMORY:-1024m}
      - JVM_MAXIMUM_MEMORY=${CONFLUENCE_MAXIMUM_MEMORY:-1024m}
      - JVM_RESERVED_CODE_CACHE_SIZE=${CONFLUENCE_RESERVED_CODE_CACHE_SIZE:-256m}
      # 注册代理路径
      - JAVA_OPTS=-javaagent:/opt/atlassian/confluence/confluence/WEB-INF/lib/atlassian-agent-1.3.1.jar
      # 时区
      - TZ=Asia/Shanghai
    volumes:
      # 数据卷
      - confluence-data:/var/atlassian/application-data/confluence
      # MySQL 8.0 连接器
      - ./utils/mysql-connector-java-8.0.29.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-java-8.0.29.jar
      # 注册代理
      - ./utils/atlassian-agent-1.3.1.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/atlassian-agent-1.3.1.jar
    depends_on:
      - confluence-mysql

  bitbucket:
    image: atlassian/bitbucket:${BITBUCKET_VERSION:-latest}
    container_name: bitbucket
    restart: unless-stopped
    ports:
      - ${BITBUCKET_PORT:-7990}:7990
    environment:
      # 代理服务器
      - SERVER_PROXY_NAME=${BITBUCKET_PROXY_NAME:-bitbucket.example.com}
      - SERVER_PROXY_PORT=${BITBUCKET_PROXY_PORT:-80}
      - SERVER_SCHEME=${BITBUCKET_SCHEME:-http}
      - SERVER_SECURE=${BITBUCKET_SECURE:-false}
      # 内存
      - JVM_MINIMUM_MEMORY=${BITBUCKET_MINIMUM_MEMORY:-512m}
      - JVM_MAXIMUM_MEMORY=${BITBUCKET_MAXIMUM_MEMORY:-1024m}
      # 注册代理路径
      - JVM_SUPPORT_RECOMMENDED_ARGS=-javaagent:/opt/atlassian/bitbucket/app/WEB-INF/lib/atlassian-agent-1.3.1-bitbucket.jar
      # 时区
      - TZ=Asia/Shanghai
    volumes:
      # 数据卷
      - bitbucket-data:/var/atlassian/application-data/bitbucket
      # MySQL 5.1 连接器（不支持 8.0 连接器）
      - ./utils/mysql-connector-java-5.1.49.jar:/opt/atlassian/bitbucket/app/WEB-INF/lib/mysql-connector-java-5.1.49.jar
      # 注册代理（不能生成授权码）
      - ./utils/atlassian-agent-1.3.1-bitbucket.jar:/opt/atlassian/bitbucket/app/WEB-INF/lib/atlassian-agent-1.3.1-bitbucket.jar
    depends_on:
      - bitbucket-mysql

  jira-mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: jira-mysql
    restart: unless-stopped
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_bin,
        --default-storage-engine=INNODB,
        --innodb-default-row-format=DYNAMIC,
        --innodb-log-file-size=2G
      ]
    environment:
      # root 密码
      - MYSQL_ROOT_PASSWORD=${JIRA_MYSQL_ROOT_PASSWORD:-atlassian}
      # 数据库名
      - MYSQL_DATABASE=${JIRA_MYSQL_DATABASE:-jira}
      # 用户名
      - MYSQL_USER=${JIRA_MYSQL_USER:-jira}
      # 密码
      - MYSQL_PASSWORD=${JIRA_MYSQL_PASSWORD:-jira}
      # 时区
      - TZ=Asia/Shanghai
    volumes:
      - jira-mysql:/var/lib/mysql

  confluence-mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: confluence-mysql
    restart: unless-stopped
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_bin,
        --default-storage-engine=INNODB,
        --max-allowed-packet=256M,
        --innodb-log-file-size=2G,
        --transaction-isolation=READ-COMMITTED,
        --binlog-format=ROW,
        --log-bin-trust-function-creators=1
      ]
    environment:
      # root 密码
      - MYSQL_ROOT_PASSWORD=${CONFLUENCE_MYSQL_ROOT_PASSWORD:-atlassian}
      # 数据库名
      - MYSQL_DATABASE=${CONFLUENCE_MYSQL_DATABASE:-confluence}
      # 用户名
      - MYSQL_USER=${CONFLUENCE_MYSQL_USER:-confluence}
      # 密码
      - MYSQL_PASSWORD=${CONFLUENCE_MYSQL_PASSWORD:-confluence}
      # 时区
      - TZ=Asia/Shanghai
    volumes:
      - confluence-mysql:/var/lib/mysql

  bitbucket-mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: bitbucket-mysql
    restart: unless-stopped
    command:
      [
        mysqld,
        --character-set-server=utf8,
        --collation-server=utf8_bin,
        --binlog-format=MIXED,
        --transaction-isolation=READ-COMMITTED
      ]
    environment:
      # root 密码
      - MYSQL_ROOT_PASSWORD=${BITBUCKET_MYSQL_ROOT_PASSWORD:-atlassian}
      # 数据库名
      - MYSQL_DATABASE=${BITBUCKET_MYSQL_DATABASE:-bitbucket}
      # 用户名
      - MYSQL_USER=${BITBUCKET_MYSQL_USER:-bitbucket}
      # 密码
      - MYSQL_PASSWORD=${BITBUCKET_MYSQL_PASSWORD:-bitbucket}
      # 时区
      - TZ=Asia/Shanghai
    volumes:
      - bitbucket-mysql:/var/lib/mysql

networks:
  default:
    name: atlassian
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET:-172.23.0.0/16}

volumes:
  jira-data:
  confluence-data:
  bitbucket-data:
  jira-mysql:
  confluence-mysql:
  bitbucket-mysql:
