version: '3.9'

services:
  jira:
    container_name: jira
    restart: always
    image: atlassian/jira-software:latest
    ports:
      - 8080:8080
    environment:
      # 下面四个环境变量用来配置 /opt/atlassian/jira/conf/server.xml，参考自 /opt/atlassian/etc/server.xml.j2
      - ATL_TOMCAT_SECURE=true
      - ATL_TOMCAT_SCHEME=https
      - ATL_PROXY_NAME=jira.atlassian.com
      - ATL_PROXY_PORT=443
      # 注册代理路径
      - JAVA_OPTS=-javaagent:/opt/atlassian/jira/atlassian-agent-1.3.1.jar
      # 中国上海时区
      - TZ=Asia/Shanghai
    volumes:
      # 数据文件夹
      - ./jira/data:/var/atlassian/application-data/jira
      # 注册代理
      - ./atlassian-agent-1.3.1.jar:/opt/atlassian/jira/atlassian-agent-1.3.1.jar
      # MySQL 8.0 连接器
      - ./mysql-connector-java-8.0.29.jar:/opt/atlassian/jira/atlassian-jira/WEB-INF/lib/mysql-connector-java-8.0.29.jar
    networks:
      atlassian:
        ipv4_address: 172.20.0.2
    depends_on:
      - jira-mysql

  confluence:
    container_name: confluence
    restart: always
    image: atlassian/confluence:latest
    ports:
      - 8090:8090
      # 协同编辑
      - 8091:8091
    environment:
      # 下面四个环境变量用来配置 /opt/atlassian/jira/conf/server.xml，参考自 /opt/atlassian/etc/server.xml.j2
      - ATL_TOMCAT_SECURE=true
      - ATL_TOMCAT_SCHEME=https
      - ATL_PROXY_NAME=confluence.atlassian.com
      - ATL_PROXY_PORT=443
      # 注册代理路径
      - JAVA_OPTS=-javaagent:/opt/atlassian/confluence/atlassian-agent-1.3.1.jar
      # 中国上海时区
      - TZ=Asia/Shanghai
    volumes:
      # 数据文件夹
      - ./confluence/data:/var/atlassian/application-data/confluence
      # 注册代理
      - ./atlassian-agent-1.3.1.jar:/opt/atlassian/confluence/atlassian-agent-1.3.1.jar
      # MySQL 8.0 连接器
      - ./mysql-connector-java-8.0.29.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-java-8.0.29.jar
    networks:
      atlassian:
        ipv4_address: 172.20.0.3
    depends_on:
      - conf-mysql

  jira-mysql:
    container_name: jira-mysql
    restart: always
    image: mysql:8.0
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_bin,
        --default-storage-engine=INNODB,
        --innodb-default-row-format=DYNAMIC,
        --innodb-log-file-size=2G
      ]
    environment:
      # root 密码
      - MYSQL_ROOT_PASSWORD=atlassian
      # 数据库名
      - MYSQL_DATABASE=jira
      # 用户名
      - MYSQL_USER=jira
      # 密码
      - MYSQL_PASSWORD=jira
    volumes:
      - ./jira/mysql:/var/lib/mysql
    networks:
      atlassian:
        ipv4_address: 172.20.0.4

  conf-mysql:
    container_name: conf-mysql
    restart: always
    image: mysql:8.0
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_bin,
        --default-storage-engine=INNODB,
        --max-allowed-packet=256M,
        --innodb-log-file-size=2G,
        --transaction-isolation=READ-COMMITTED,
        --binlog-format=ROW,
        --log-bin-trust-function-creators=1
      ]
    environment:
      # root 密码
      - MYSQL_ROOT_PASSWORD=atlassian
      # 数据库名
      - MYSQL_DATABASE=confluence
      # 用户名
      - MYSQL_USER=confluence
      # 密码
      - MYSQL_PASSWORD=confluence
    volumes:
      - ./confluence/mysql:/var/lib/mysql
    networks:
      atlassian:
        ipv4_address: 172.20.0.5

networks:
  atlassian:
    name: atlassian
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  jira:
  confluence:
  jira-mysql:
  conf-mysql:
